# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6o-s7-h4SsNMCv8CbefJAFA-k8zx-BZ
"""

import gradio as gr
import pandas as pd

def analyze_with_medquad(file, text_input):
    # Read uploaded file or textbox input
    if file is not None:
        file_path = file if isinstance(file, str) else file.name
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()
    elif text_input and text_input.strip():
        text = text_input.strip()
    else:
        empty_df = pd.DataFrame(columns=["entity_text", "entity_type", "matched_question", "medquad_answer"])
        grouped_df = pd.DataFrame(columns=["Category", "Entities"])
        return "No input provided.", empty_df, grouped_df, "No entities found."

    # Run NER
    entities = predict_entities(text, model, tokenizer)

    if len(entities) == 0:
        detailed_df = pd.DataFrame(columns=["entity_text", "entity_type", "matched_question", "medquad_answer"])
        grouped_df = pd.DataFrame(columns=["Category", "Entities"])
        summary = "No disease or chemical entities were found."
    else:
        enriched_entities = enrich_entities_with_medquad(entities, medquad_ds["train"])
        detailed_df = pd.DataFrame(enriched_entities).drop_duplicates().reset_index(drop=True)

        diseases = detailed_df[detailed_df["entity_type"] == "Disease"]["entity_text"].drop_duplicates().tolist()
        chemicals = detailed_df[detailed_df["entity_type"] == "Chemical"]["entity_text"].drop_duplicates().tolist()

        grouped_df = pd.DataFrame([
            {
                "Category": "Diseases",
                "Entities": ", ".join(diseases) if diseases else "None"
            },
            {
                "Category": "Chemicals",
                "Entities": ", ".join(chemicals) if chemicals else "None"
            }
        ])

        summary = build_grouped_summary(detailed_df)

    return text, detailed_df, grouped_df, summary

demo = gr.Interface(
    fn=analyze_with_medquad,
    inputs=[
        gr.File(label="Upload Patient Report (.txt)", file_types=[".txt"]),
        gr.Textbox(
            label="Or Paste Medical Text Here",
            lines=12,
            placeholder="Paste a patient report or medical paragraph here..."
        )
    ],
    outputs=[
        gr.Textbox(label="Input Text", lines=12),
        gr.Dataframe(label="Extracted Entities + MedQuAD Explanations"),
        gr.Dataframe(label="Grouped Output"),
        gr.Textbox(label="Summary", lines=8)
    ],
    title="Biomedical NER + MedQuAD Explanation Assistant",
    description="Upload a patient report or paste medical text. The system extracts disease and chemical entities using BioBERT and retrieves related explanations from MedQuAD."
)

demo.launch(share=True)