# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0KBqNPynPLuLIRz_wXltm3rePloJL4E
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd
import torch
from datasets import load_from_disk
from transformers import AutoModelForTokenClassification, AutoTokenizer


class BiomedicalNERInference:
    def __init__(
        self,
        model_path: str,
        medquad_path: Optional[str] = None,
        device: Optional[str] = None,
        max_length: int = 512,
    ) -> None:
        self.model_path = str(model_path)
        self.medquad_path = medquad_path
        self.max_length = max_length

        if device is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"
        self.device = device

        self.tokenizer = AutoTokenizer.from_pretrained(self.model_path)
        self.model = AutoModelForTokenClassification.from_pretrained(self.model_path)
        self.model.to(self.device)
        self.model.eval()

        self.id2label: Dict[int, str] = self.model.config.id2label
        self.medquad_ds = None
        if self.medquad_path:
            self.medquad_ds = load_from_disk(self.medquad_path)

    @staticmethod
    def _merge_wordpiece_tokens(tokens: List[str]) -> List[str]:
        merged: List[str] = []
        for tok in tokens:
            if tok.startswith("##") and merged:
                merged[-1] = merged[-1] + tok[2:]
            else:
                merged.append(tok)
        return merged

    def predict_entities(self, text: str) -> List[Dict[str, str]]:
        if not isinstance(text, str) or not text.strip():
            return []

        inputs = self.tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length,
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = self.model(**inputs)

        pred_ids = torch.argmax(outputs.logits, dim=2)[0].tolist()
        input_ids = inputs["input_ids"][0].detach().cpu().tolist()
        tokens = self.tokenizer.convert_ids_to_tokens(input_ids)

        entities: List[Dict[str, str]] = []
        current_tokens: List[str] = []
        current_type: Optional[str] = None

        for token, pred_id in zip(tokens, pred_ids):
            label = self.id2label[int(pred_id)]

            if token in self.tokenizer.all_special_tokens:
                continue

            if label.startswith("B-"):
                if current_tokens:
                    entities.append(
                        {
                            "entity_text": " ".join(self._merge_wordpiece_tokens(current_tokens)),
                            "entity_type": current_type or "",
                        }
                    )
                current_tokens = [token]
                current_type = label[2:]

            elif label.startswith("I-") and current_type == label[2:]:
                current_tokens.append(token)

            else:
                if current_tokens:
                    entities.append(
                        {
                            "entity_text": " ".join(self._merge_wordpiece_tokens(current_tokens)),
                            "entity_type": current_type or "",
                        }
                    )
                    current_tokens = []
                    current_type = None

        if current_tokens:
            entities.append(
                {
                    "entity_text": " ".join(self._merge_wordpiece_tokens(current_tokens)),
                    "entity_type": current_type or "",
                }
            )

        cleaned: List[Dict[str, str]] = []
        seen = set()
        for ent in entities:
            key = (ent["entity_text"].strip(), ent["entity_type"].strip())
            if key[0] and key not in seen:
                seen.add(key)
                cleaned.append(
                    {
                        "entity_text": key[0],
                        "entity_type": key[1],
                    }
                )

        return cleaned

    @staticmethod
    def group_entities(entities: List[Dict[str, str]]) -> Dict[str, List[str]]:
        grouped = {"Disease": [], "Chemical": []}
        seen = {"Disease": set(), "Chemical": set()}

        for ent in entities:
            etype = ent.get("entity_type", "")
            etext = ent.get("entity_text", "").strip()

            if etype in grouped and etext and etext not in seen[etype]:
                grouped[etype].append(etext)
                seen[etype].add(etext)

        return grouped

    @staticmethod
    def build_summary(entities: List[Dict[str, str]]) -> str:
        grouped = BiomedicalNERInference.group_entities(entities)
        diseases = grouped["Disease"]
        chemicals = grouped["Chemical"]

        if not diseases and not chemicals:
            return "No disease or chemical entities were found."

        lines = [
            f"Total entities found: {len(entities)}",
            f"Diseases found: {len(diseases)}",
            f"Chemicals found: {len(chemicals)}",
        ]

        if diseases:
            lines.append("Diseases: " + ", ".join(diseases))
        if chemicals:
            lines.append("Chemicals: " + ", ".join(chemicals))

        return "\n".join(lines)

    @staticmethod
    def _clean_text(text: str) -> str:
        return str(text).strip().lower()

    def retrieve_medquad_explanation(self, entity_text: str) -> Dict[str, str]:
        if self.medquad_ds is None:
            return {
                "matched_question": "MedQuAD not loaded",
                "matched_answer": "No explanation available.",
            }

        entity = self._clean_text(entity_text)
        if not entity:
            return {
                "matched_question": "No matching MedQuAD question found",
                "matched_answer": "No explanation available.",
            }

        matches: List[Dict[str, str]] = []
        split = self.medquad_ds["train"]

        for item in split:
            question = self._clean_text(item.get("question", ""))
            answer = str(item.get("answer", "")).strip()

            if not question or not answer:
                continue

            if entity in question:
                matches.append(
                    {
                        "matched_question": item.get("question", ""),
                        "matched_answer": answer,
                    }
                )

        if not matches:
            return {
                "matched_question": "No matching MedQuAD question found",
                "matched_answer": "No explanation available from MedQuAD.",
            }

        return matches[0]

    def enrich_entities_with_medquad(self, entities: List[Dict[str, str]]) -> List[Dict[str, str]]:
        enriched: List[Dict[str, str]] = []

        for ent in entities:
            medquad_match = self.retrieve_medquad_explanation(ent["entity_text"])
            enriched.append(
                {
                    "entity_text": ent["entity_text"],
                    "entity_type": ent["entity_type"],
                    "matched_question": medquad_match["matched_question"],
                    "medquad_answer": medquad_match["matched_answer"],
                }
            )

        return enriched

    def analyze_text(self, text: str) -> Dict[str, object]:
        entities = self.predict_entities(text)
        grouped = self.group_entities(entities)
        summary = self.build_summary(entities)

        enriched_entities = self.enrich_entities_with_medquad(entities) if self.medquad_ds else entities

        detailed_df = pd.DataFrame(enriched_entities)
        grouped_df = pd.DataFrame(
            [
                {
                    "Category": "Diseases",
                    "Entities": ", ".join(grouped["Disease"]) if grouped["Disease"] else "None",
                },
                {
                    "Category": "Chemicals",
                    "Entities": ", ".join(grouped["Chemical"]) if grouped["Chemical"] else "None",
                },
            ]
        )

        return {
            "entities": entities,
            "grouped": grouped,
            "summary": summary,
            "detailed_df": detailed_df,
            "grouped_df": grouped_df,
        }


if __name__ == "__main__":
    # Change these paths to match your repo layout
    model_path = "final_biobert_bc5cdr"
    medquad_path = "medquad_ds"

    ner = BiomedicalNERInference(
        model_path=model_path,
        medquad_path=medquad_path,
    )

    sample_text = """
    The patient has hypertension, prediabetes, and anemia.
    Medications include acetaminophen.
    Recent observations show elevated glucose.
    """

    result = ner.analyze_text(sample_text)

    print("Entities:")
    for entity in result["entities"]:
        print(entity)

    print("\nSummary:")
    print(result["summary"])

    print("\nDetailed DataFrame:")
    print(result["detailed_df"].head())